server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    check-template: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html