server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    check-template: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html



# github信息
github:
  client:
    id: 70b646246b5e266e5a3d
    secret: 5db2e54b65f63e847948e3cfd33a76d29dce9d21
  redirect:
    uri: http://localhost:8081/callback